import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { compactResearchPackage } from '../scripts/compact-research-package.mjs';
import { copyPublicPackage } from '../scripts/copy-public-package.mjs';
import { decodeAccountEvidence } from '../src/accountEvidence.js';

test('compaction preserves decoded claims, base files and historical bytes; repeat builds stay stable', async t => {
  const dir = await mkdtemp(path.join(tmpdir(), 'compact-research-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const root = path.join(dir, 'repo/public/data'), archive = path.join(dir, 'archive');
  await mkdir(path.join(root, 'account-evidence'), { recursive: true });
  const detail = { account_key: 'HU:A001', claims: [{ claim_id: 'retained', observations: [{ evidence: 'Doctor clinic contact '.repeat(500) }] }] };
  const payload = JSON.stringify(detail), sha = createHash('sha256').update(payload).digest('hex');
  const name = `account-evidence/A001-${sha.slice(0, 16)}.json`, old = 'account-evidence/A001-bbbbbbbbbbbbbbbb.json';
  const status = { dataset_id: 'test', base_data_hash: 'base', research_snapshot_id: 'snapshot' };
  const index = { ...status, evidence_storage: 'account-files-v1', accounts: [{ ...detail, evidence_path: name, evidence_sha256: sha }] };
  for (const [file, bytes] of Object.entries({ 'account-enrichment.json': JSON.stringify(index), 'account-research-status.json': JSON.stringify(status), 'email-validation-seed.json': 'human decisions', [name]: payload, [old]: 'old immutable evidence' })) await writeFile(path.join(root, file), bytes);
  await assert.rejects(compactResearchPackage(root, path.join(root, 'archive')), /outside the repository/);
  const result = await compactResearchPackage(root, archive);
  assert.equal(result.archivedFiles, 2);
  assert.ok(result.currentBytes < result.originalBytes / 4);
  const updated = JSON.parse(await readFile(path.join(root, 'account-enrichment.json'))), account = updated.accounts[0];
  const saved = await readFile(path.join(root, account.evidence_path), 'utf8');
  assert.deepEqual(JSON.parse(await decodeAccountEvidence(saved, account.evidence_encoding)), detail);
  assert.equal(gunzipSync(await readFile(path.join(archive, path.basename(name) + '.gz'))).toString(), payload);
  assert.equal(gunzipSync(await readFile(path.join(archive, path.basename(old) + '.gz'))).toString(), 'old immutable evidence');
  assert.equal(await readFile(path.join(root, 'email-validation-seed.json'), 'utf8'), 'human decisions');
  assert.equal((await readdir(path.join(root, 'account-evidence'))).length, 1);
  const second = await compactResearchPackage(root, archive);
  assert.equal(second.archivedFiles, 0);
  assert.deepEqual(JSON.parse(await readFile(path.join(root, 'account-enrichment.json'))), updated);
  const dist = path.join(dir, 'dist');
  await copyPublicPackage(path.join(root, '..'), dist);
  assert.equal(await readFile(path.join(dist, 'data', account.evidence_path), 'utf8'), saved);
  await writeFile(path.join(root, account.evidence_path), saved + 'corrupt');
  await assert.rejects(compactResearchPackage(root, archive), /evidence changed/);
  assert.deepEqual(JSON.parse(await readFile(path.join(root, 'account-enrichment.json'))), updated);
});
