import { computed, ref, watch } from 'vue';
import { fieldState, researchFields, contactFields, contactPresentation, contactPreferenceState } from './accountEvidence.js';
import { associationKey, resolvedAssociations, safeSourceUrl } from './associations.js';
import ContactCandidateReview from './ContactCandidateReview.js';
export default {
  components:{ContactCandidateReview},
  props:{pkg:Object, associations:Object, fieldDecisions:Array, associationDecisions:Array, preferences:{type:Array,default:()=>[]},validity:{type:Object,default:()=>({})},reviewer:String, saving:Boolean, error:String},
  emits:['field-decision','association-decision','preference','export','load-account'],
  setup(props,{emit}) {
    const search=ref(new URLSearchParams(location.hash.slice(1)).get('account')||''), selected=ref(''), status=ref('pending'),lane=ref('all'),view=ref('contacts'),sourceLimit=ref(30),accountLimit=ref(150);
    const associationMap=computed(()=>new Map(resolvedAssociations(props.associations,props.associationDecisions).map(a=>[a.id,a])));
    function state(c){return c.field==='email'&&c.account_key.startsWith('HU:') ? associationMap.value.get(associationKey(c.value,c.account_key.slice(3))) || {...c,status:'unreviewed',heads:[]} : fieldState(c,props.fieldDecisions);}
    const emailsByAccount=computed(()=>{const result=new Map();for(const a of associationMap.value.values()){const key='HU:'+a.provider_code;if(!result.has(key))result.set(key,[]);result.get(key).push(a);}return result;});
    const accounts=computed(()=>(props.pkg?.accounts||[]).filter(a=>(!search.value||[a.account_key,a.name,...a.services.flatMap(s=>[s.doctor,s.city]),...a.claims.map(c=>c.value),...(emailsByAccount.value.get(a.account_key)||[]).map(a=>a.email)].join(' ').toLowerCase().includes(search.value.toLowerCase())) && (lane.value==='all'||lane.value==='software_unresolved'&&a.claims.some(c=>c.field==='practice_software'&&c.attribution?.eligible_for_analytics===false&&state(c).status!=='rejected')||lane.value==='software_candidates'&&a.claims.some(c=>c.field==='practice_software'&&c.attribution?.eligible_for_analytics===true&&state(c).status!=='rejected')||lane.value==='sample'&&(a.contact_summary||a.contact_reconciliation)?.review_sample||(a.contact_summary||a.contact_reconciliation)?.lanes?.includes(lane.value)) && (status.value==='all'||(emailsByAccount.value.get(a.account_key)||[]).some(a=>['unreviewed','conflict'].includes(a.status))||a.claims.some(c=>['unreviewed','conflict'].includes(state(c).status)))));
    const current=computed(()=>accounts.value.find(a=>a.account_key===selected.value)||accounts.value[0]);
    const ready=computed(()=>props.pkg?.evidence_storage!=='account-files-v1'||current.value?.evidence_loaded);
    const contacts=computed(()=>ready.value&&current.value?contactPresentation(current.value,props.fieldDecisions,associationMap.value,props.preferences,props.validity):null);
    const otherClaims=computed(()=>!ready.value?[]:current.value.claims.filter(c=>!contacts.value||!contactFields.includes(c.field)));
    watch(()=>[current.value?.account_key,props.pkg?.research_snapshot_id],()=>{sourceLimit.value=30;if(current.value&&!ready.value)emit('load-account',current.value.account_key);},{immediate:true});
    watch(lane, value=>{if(value.startsWith('software_'))view.value='other';accountLimit.value=150;});
    function save(c,status){
      const s=state(c), common={id:crypto.randomUUID(),status,reviewed_by:props.reviewer||'reviewer',reviewed_at:new Date().toISOString(),supersedes:s.heads||[],source:'account-evidence-review'};
      if(c.field==='email'&&c.account_key.startsWith('HU:'))emit('association-decision',{...common,association_id:associationKey(c.value,c.account_key.slice(3)),email:c.value,provider_code:c.account_key.slice(3),country:'HU',contact_role:s.contact_role||'unknown',...(s.contact_purpose?{contact_purpose:s.contact_purpose}:{}),owner_name:s.owner_name||'',note:'',evidence_urls:c.observations.map(o=>o.source_url).filter(safeSourceUrl)});
      else emit('field-decision',{...common,claim_id:c.claim_id,account_key:c.account_key,field:c.field,observation_ids:c.observations.map(o=>o.observation_id),...(contactFields.includes(c.field)&&s.contact_role?{contact_role:s.contact_role}:{})});
    }
    function reviewContact({group,status,role}){
      const audit=heads=>({id:crypto.randomUUID(),status,reviewed_by:props.reviewer||'reviewer',reviewed_at:new Date().toISOString(),supersedes:heads||[],source:'account-contact-review'});
      if(group.field==='email'&&current.value.account_key.startsWith('HU:')){
        const s=associationMap.value.get(group.association_id)||{heads:[]};
        emit('association-decision',{...audit(s.heads),association_id:associationKey(group.value,current.value.provider_code),email:group.value,provider_code:current.value.provider_code,country:'HU',contact_role:role==='doctor'?'doctor_staff':role==='shared'?'shared_contact':'clinic_contact',contact_purpose:role,owner_name:s.owner_name||'',note:s.note||'',evidence_urls:group.proofs.map(p=>p.source_url).filter(safeSourceUrl)});
      }else{
        const claims=current.value.claims.filter(c=>group.claim_ids.includes(c.claim_id));
        emit('field-decision',claims.map(c=>({...audit(state(c).heads),claim_id:c.claim_id,account_key:c.account_key,field:c.field,observation_ids:c.observations.map(o=>o.observation_id),contact_role:role})));
      }
    }
    function prefer(field,group=null){const choice=contactPreferenceState(current.value,field,props.preferences);emit('preference',{id:crypto.randomUUID(),schema_version:1,account_key:current.value.account_key,field,candidate_id:group?.id||null,reviewed_by:props.reviewer||'reviewer',reviewed_at:new Date().toISOString(),supersedes:choice.heads,source:'account-contact-review'});}
    return {search,selected,status,lane,view,sourceLimit,accountLimit,accounts,current,ready,contacts,otherClaims,state,save,reviewContact,prefer,researchFields,contactFields,safeSourceUrl};
  },
  template:`<section class="account-evidence-workspace"><h1>Account data</h1><p><b>* Needs review.</b> Contact ownership, email validity and preferred-contact selection are separate decisions. Recommendations do not confirm a value.</p><p>Export review JSON and import it into the market dashboard to transfer your decisions.</p><p v-if="!pkg" role="status">Account evidence is unavailable. Existing email reviews remain available.</p><template v-else>
    <div class="mapping-controls"><label>Find account, doctor, email or software<input v-model="search" type="search"></label><label>Show<select v-model="status" aria-label="Show"><option value="pending">Needs review</option><option value="all">All accounts</option></select></label><label>Review queue<select v-model="lane" aria-label="Review queue"><option value="all">All cases</option><option value="sample">Reviewer assessment sample</option><option value="software_unresolved">Software attribution unresolved</option><option value="software_candidates">Attributable software candidates</option><option value="recommended_contacts">Recommended contacts</option><option value="identity_ambiguity">Doctor identity ambiguity</option><option value="shared_email">Shared emails</option><option value="historical">Historical evidence</option><option value="multiple_services">Multiple services</option><option value="limited_evidence">Limited evidence</option></select></label><button @click="$emit('export')">Export review JSON</button></div>
    <p>{{accounts.length}} accounts · {{pkg.registry_snapshot}}</p><p v-if="lane==='sample'">This sample covers different evidence conditions. Its accuracy has not yet been assessed by a human.</p>
    <div class="account-evidence-layout"><nav aria-label="Accounts"><button v-for="a in accounts.slice(0,accountLimit)" :key="a.account_key" @click="selected=a.account_key" :class="{active:current?.account_key===a.account_key}">{{a.name}} · {{a.account_key}}<small>{{['PL','RO'].includes(pkg.country)?(a.locations?.length||0)+(pkg.country==='RO'?' dated contact row(s)':' registered location(s)'):a.services.length+' service(s)'}} · {{a.contact_summary?.source_count||0}} supporting sources</small></button><button v-if="accounts.length>accountLimit" @click="accountLimit+=150">Show 150 more accounts</button></nav>
    <main v-if="current"><h2>{{current.name}} · {{current.account_key}}</h2><p>{{current.coverage}}</p><details open><summary>Recorded doctors and service locations</summary><p v-for="s in current.services" :key="s.hsz">{{s.doctor}} · {{s.city}} · {{s.address}} · HSZ {{s.hsz}}</p><p v-if="['PL','RO'].includes(pkg.country)">{{pkg.country==='RO'?'CIF':'NIP'}} {{current.business_entity_code||'not recorded'}}</p><p v-for="(place,i) in current.locations||[]" :key="i">{{place.name}} · {{place.address}}<small v-if="pkg.country==='RO'">{{place.scope}}</small></p><p v-for="(contact,i) in current.recorded_contacts||[]" :key="'recorded-'+i"><b>{{contact.label}}:</b> {{contact.value}} · {{contact.source_date}} <a v-if="safeSourceUrl(contact.source_url)" :href="safeSourceUrl(contact.source_url)" target="_blank" rel="noopener noreferrer">Source</a></p></details>
    <p v-if="!ready" role="status">Loading account evidence… <button v-if="error" @click="$emit('load-account',current.account_key)">Retry evidence</button></p>
    <template v-if="ready&&contacts"><label>Account review section<select v-model="view" aria-label="Account review section"><option value="contacts">Contacts</option><option value="sources">Supporting sources ({{contacts.sources.length}})</option><option value="other">Software and other data</option></select></label>
      <section v-if="view==='contacts'"><section v-for="field in contactFields" :key="field"><h3>Preferred {{field==='email'?'email':field==='website'?'practice website':'telephone'}}</h3><p v-if="contacts.choices[field].kind==='suggested'">Suggested for review. No human preference has been recorded.</p><p v-else-if="contacts.choices[field].kind==='conflict'" role="status">Reviewers selected different contacts. Choose one below to resolve the conflict.</p><p v-else-if="['stale','unavailable'].includes(contacts.choices[field].kind)" role="status">The selected contact is unavailable, rejected or no longer eligible. Choose a replacement explicitly.</p><p v-else-if="contacts.choices[field].kind==='cleared'">Reviewer left the preferred contact unset.</p><p v-else-if="!contacts.preferred[field]">{{current.contact_reconciliation.recommendation_reasons?.[field]||'No preferred contact recorded.'}}</p>
      <ContactCandidateReview :market="pkg.country||'HU'" v-if="contacts.preferred[field]" :group="contacts.preferred[field]" :saving="saving" :preferred="contacts.choices[field].kind==='selected'" @review="reviewContact" @prefer="prefer(field,$event)"/><button :disabled="saving||contacts.choices[field].kind==='cleared'" @click="prefer(field)">Leave preferred {{field}} unset</button></section>
      <details class="contact-alternatives"><summary>Other contacts and alternatives ({{contacts.alternatives.length}})</summary><ContactCandidateReview :market="pkg.country||'HU'" v-for="group in contacts.alternatives" :key="group.id" :group="group" :saving="saving" @review="reviewContact" @prefer="prefer(group.field,$event)"/></details></section>
      <section v-if="view==='sources'"><h3>Supporting sources</h3><p>These pages support research. They are not presented as the clinic's own website unless their role is explicitly reviewed.</p><ContactCandidateReview :market="pkg.country||'HU'" v-for="group in contacts.sources.slice(0,sourceLimit)" :key="group.id" :group="group" :saving="saving" @review="reviewContact" @prefer="prefer(group.field,$event)"/><button v-if="contacts.sources.length>sourceLimit" @click="sourceLimit+=30">Show 30 more sources</button></section>
    </template>
    <template v-if="ready&&(!contacts||view==='other')"><p v-if="!otherClaims.length">No other candidate values retained. This does not prove absence.</p><article v-for="c in otherClaims" :key="c.claim_id" class="mapping-card"><h3>{{researchFields[c.field]}}: {{c.value}}<sup v-if="['unreviewed','conflict'].includes(state(c).status)">*</sup></h3><p>{{state(c).status}} · {{['PL','RO'].includes(pkg.country)?'Account-level candidate':'Claim recorded under HSZ '+c.hsz}}</p><section v-if="c.attribution"><p><b>{{c.attribution.status.replaceAll('_',' ')}}</b> · Supported scope: {{c.attribution.scope}}</p><p>{{state(c).status==='confirmed'?'Account attribution accepted by reviewer.':c.attribution.eligible_for_analytics?'Included as an unverified attributable candidate.':'Excluded from attributed competitor totals; retained for review.'}} Current use and use by every panel are not verified.</p><ul><li v-for="reason in c.attribution.reasons" :key="reason">{{reason}}</li></ul><details v-if="c.attribution.proofs.length"><summary>Attribution passages</summary><div v-for="(p,i) in c.attribution.proofs" :key="i"><blockquote>{{p.excerpt}}</blockquote><a v-if="safeSourceUrl(p.source_url)" :href="safeSourceUrl(p.source_url)" target="_blank" rel="noopener noreferrer">Open attribution source</a></div></details></section><details><summary>Evidence ({{c.observations.length}})</summary><div v-for="o in c.observations" :key="o.observation_id"><p>{{o.method}} · {{o.retrieved_at||'Date unavailable'}} · {{o.temporal_status}}</p><blockquote>{{o.evidence}}</blockquote><p>{{o.identity_basis}}</p><a v-if="safeSourceUrl(o.source_url)" :href="safeSourceUrl(o.source_url)" target="_blank" rel="noopener noreferrer">Open source</a></div></details><div class="mapping-actions"><button :disabled="saving" @click="save(c,'confirmed')">{{c.field==='email'?'Confirm clinic link':c.attribution?'Confirm account attribution':'Confirm value'}}</button><button :disabled="saving" @click="save(c,'rejected')">Reject</button><button :disabled="saving" @click="save(c,'unreviewed')">Leave unresolved</button></div></article></template>
    </main></div></template><p v-if="error" role="alert">{{error}}</p><p v-if="saving" role="status">Saving…</p></section>`
};
